### PR TITLE
FOGL-2356: fix log message when Pyth method is not found

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-2356: fix log message when Pyth method is not found

### CODE REVIEW

**Comment by shariq1501** [comment]
@pintomax Warning message looks fine but once the script is uploaded with different name say readings.py then there are some recurring fatal errors related to plugin flooded the syslog. Check below

```
Mar  6 12:56:13 Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:13 Random[7519]: FATAL: Filter python35 error: cannot find Python 3.5 method 'readings' in loaded module 'random_py35_script_readings.py'
Mar  6 12:56:13  Random[7519]: ERROR: Filter 'python35' (python35), script 'random_py35_script_readings', filter error, action: pass unfiltered data onwards
Mar  6 12:56:13  Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:18  Random[7519]: ERROR: Filter 'python35' (python35), script 'random_py35_script_readings', filter error, action: pass unfiltered data onwards
Mar  6 12:56:18  Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:22  FogLAMP[7383] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Process started: Schedule 'stats collection' process 'stats collector' task 6e0ffb76-61c0-4745-8324-4330459e2dc3 pid 7616, 2 running tasks#012['tasks/statistics', '--port=38407', '--address=127.0.0.1', '--name=stats collection']
Mar  6 12:56:23  FogLAMP[7383] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Process terminated: Schedule 'stats collection' process 'stats collector' task 6e0ffb76-61c0-4745-8324-4330459e2dc3 pid 7616 exit 0, 1 running tasks#012['tasks/statistics']
Mar  6 12:56:23  FogLAMP[7383] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Scheduled task for schedule 'stats collection' to start at 2019-03-06 12:56:37.457787
Mar  6 12:56:23  Random[7519]: ERROR: Filter 'python35' (python35), script 'random_py35_script_readings', filter error, action: pass unfiltered data onwards
Mar  6 12:56:23  Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:28  Random[7519]: ERROR: Filter 'python35' (python35), script 'random_py35_script_readings', filter error, action: pass unfiltered data onwards
Mar  6 12:56:28  Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:34  Random[7519]: ERROR: Filter 'python35' (python35), script 'random_py35_script_readings', filter error, action: pass unfiltered data onwards
Mar  6 12:56:34  Random[7519]: FATAL: Filter 'python35', script 'random_py35_script_readings': Error 'no description'
Mar  6 12:56:37  FogLAMP[7383] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Process started: Schedule 'stats collection' process 'stats collector' task d991b048-8840-4119-8141-fe4b2302fc11 pid 7637, 2 running tasks#012['tasks/statistics', '--port=38407', '--address=127.0.0.1', '--name=stats collection']
```

**Comment by shariq1501** [comment]
@pintomax update category item for enable/disable mode is required. 
```
enable: {
displayName: "Enabled",
value: "true",
type: "boolean",
default: "false",
description: "A switch that can be used to enable or disable execution of the Python 3.5 filter."
}
```

**Comment by pintomax** [comment]
@mshariq-nerd Just checked C++ plugins don't have any handle to configuration manager client, so it's not possible to update the category from the plugin code.

Let's find another solution.

**Comment by pintomax** [comment]
@mshariq-nerd As we agreed, current solution is: keep logging and don't disable filter

**Review by shariq1501 — APPROVED** [review]

**Pull request merged**
